version: 2
  
python:
  version: 3.7
  system_packages: true
  # Install our python package before building the docs
  install:
    - requirements: requirements.txt


sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
